version: '3'

services:
  app:
    container_name: "app"
    build:
      context: "."
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"

  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "./sql/mysql/mysql-data-dir:/var/lib/mysql:delegated"
      - "./sql/mysql/dump:/docker-entrypoint-initdb.d"
