version: '3'

services:
  api:
    container_name: "api"
    build:
      context: "."
      dockerfile: "./docker/api/Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"

  mysql:
    container_name: "mysql"
    build:
      context: "."
      dockerfile: "./docker/mysql/Dockerfile"
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mysql/mysql-data-dir:/var/lib/mysql:delegated"
      - "./docker/mysql/dump:/docker-entrypoint-initdb.d"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
